const cfg=window.NOVA_CONFIG;
const supabaseClient=window.supabase.createClient(cfg.url,cfg.key);
let dbReady=false,currentUser=null,lang="en",currentProduct=null;
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const demoProducts=[
{name:"ASUS ROG RTX 5080",brand:"ASUS",category:"Graphics",price:429.900,old_price:507.282,discount:true,stock_qty:3,type:"gpu",description:"High-end graphics card for elite gaming builds."},
{name:"MSI RTX 4070 Super",brand:"MSI",category:"Graphics",price:219.900,old_price:249.900,discount:true,stock_qty:12,type:"gpu",description:"Great 1440p gaming graphics card."},
{name:"Ryzen 7 9800X3D",brand:"AMD",category:"Processor",price:189.900,old_price:null,discount:false,stock_qty:9,type:"cpu",description:"Gaming CPU with excellent performance."},
{name:"Samsung 990 Pro 2TB",brand:"Samsung",category:"Storage",price:59.900,old_price:70.682,discount:true,stock_qty:15,type:"ram",description:"Fast NVMe storage."},
{name:"G.Skill DDR5 32GB",brand:"G.Skill",category:"RAM",price:44.900,old_price:52.982,discount:true,stock_qty:3,type:"ram",description:"Fast DDR5 memory."},
{name:"Lian Li O11 EVO RGB",brand:"Lian Li",category:"Case",price:49.900,old_price:null,discount:false,stock_qty:3,type:"case",description:"Premium RGB case."},
{name:"Samsung Odyssey 27",brand:"Samsung",category:"Monitor",price:119.900,old_price:141.482,discount:true,stock_qty:10,type:"monitor",description:"Gaming monitor for smooth visuals."}
];
let products=[],shown=[],cart=JSON.parse(localStorage.getItem("nova_cart")||"[]"),wishlist=JSON.parse(localStorage.getItem("nova_wishlist")||"[]"),orders=JSON.parse(localStorage.getItem("nova_orders")||"[]"),addresses=JSON.parse(localStorage.getItem("nova_addresses")||"[]");
function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function money(n){return Number(n||0).toFixed(3)+" KD"}
function saveCart(){localStorage.setItem("nova_cart",JSON.stringify(cart));updateBadges()}
function saveWishlist(){localStorage.setItem("nova_wishlist",JSON.stringify(wishlist))}
function saveOrders(){localStorage.setItem("nova_orders",JSON.stringify(orders))}
function saveAddresses(){localStorage.setItem("nova_addresses",JSON.stringify(addresses))}
function updateBadges(){const count=cart.reduce((a,b)=>a+b.qty,0);$("#cartBadge").textContent=count;$("#adminCartCount")&&($("#adminCartCount").textContent=count)}
function showPage(id){$$(".page").forEach(p=>p.classList.remove("active"));const el=$("#"+id);if(el)el.classList.add("active");closeDrawer();window.scrollTo(0,0);if(id==="cart")renderCart();if(id==="orders")renderOrders();if(id==="wishlist")renderWishlist();if(id==="addresses")renderAddresses();if(id==="admin")renderAdmin();}
function openDrawer(){$("#drawer").classList.add("open");$("#overlay").classList.add("show")}
function closeDrawer(){$("#drawer").classList.remove("open");$("#overlay").classList.remove("show")}
function stockText(p){return Number(p.stock_qty)===3?"3 Left":Number(p.stock_qty)>0?"In Stock":"Out of Stock"}
function productArtType(p){return p.type||p.category?.toLowerCase()||"case"}
async function loadProducts(){try{const {data,error}=await supabaseClient.from("products").select("*").order("created_at",{ascending:false});if(error)throw error;products=(data&&data.length)?data:demoProducts;dbReady=true;$("#productsStatus").textContent="Products loaded from Supabase.";$("#adminDbStatus")&&($("#adminDbStatus").textContent="Connected")}catch(e){products=demoProducts;dbReady=false;$("#productsStatus").textContent="Using demo products. Run supabase-schema.sql to enable live database.";$("#adminDbStatus")&&($("#adminDbStatus").textContent="Demo Mode")}shown=[...products];renderBrandTools();renderProducts();renderBuilder();renderAdmin();}
function renderBrandTools(){const brands=[...new Set(products.map(p=>p.brand).filter(Boolean))];$("#brandTools").innerHTML=brands.map(b=>`<button data-brand="${b}">${b}</button>`).join("")}
function renderProducts(list=shown){$("#productsGrid").innerHTML=list.map((p,i)=>{const idx=products.indexOf(p);return `<article class="card product"><div class="product-art ${productArtType(p)}" data-open="${idx}"><div class="visual"></div><span class="tag stock">${stockText(p)}</span>${p.discount?`<span class="tag discount">Discount</span>`:""}${Number(p.stock_qty)===3?`<span class="tag lefttag">3 Left</span>`:""}</div><h3>${p.name}</h3><span class="badge">${p.brand}</span>${p.old_price?`<div class="old">${money(p.old_price)}</div>`:""}<div class="price">${money(p.price)}</div><button class="primary wide" data-add="${idx}">Add to Cart</button></article>`}).join("");$("#adminProductCount")&&($("#adminProductCount").textContent=products.length)}
function openProduct(i){currentProduct=products[i];const p=currentProduct;$("#detailTitle").textContent=p.name;$("#detailName").textContent=p.name;$("#detailDescription").textContent=p.description||"NOVA product.";$("#detailBrand").textContent=p.brand;$("#detailCategory").textContent=p.category;$("#detailPrice").textContent=money(p.price);$("#detailOld").textContent=p.old_price?money(p.old_price):"";$("#detailArt").className="product-art big "+productArtType(p);$("#detailArt").innerHTML='<div class="visual"></div>';$("#detailTags").innerHTML=`<span class="badge">${stockText(p)}</span>${p.discount?'<span class="badge">Discount</span>':""}`;showPage("product")}
function addToCart(p){if(!p)return;const id=p.id||p.name;const found=cart.find(x=>x.id===id);if(found)found.qty++;else cart.push({id,name:p.name,price:Number(p.price),qty:1});saveCart();toast("Added to cart");renderCart()}
function renderCart(){if(!cart.length){$("#cartItems").innerHTML="<h3>Your cart is empty</h3><p>Add products to continue.</p>";$("#cartCount").textContent="0";$("#cartTotal").textContent="0.000";return}$("#cartItems").innerHTML=cart.map((item,i)=>`<div class="cart-item"><div><b>${item.name}</b><br><span class="muted">NOVA Product</span></div><div class="qty"><button data-dec="${i}">−</button><span>${item.qty}</span><button data-inc="${i}">+</button></div><b>${money(item.price*item.qty)}</b><button class="remove" data-remove="${i}">Remove</button></div>`).join("");$("#cartCount").textContent=cart.reduce((a,b)=>a+b.qty,0);$("#cartTotal").textContent=cart.reduce((a,b)=>a+b.price*b.qty,0).toFixed(3)}
function filterSearch(){const q=$("#searchInput").value.toLowerCase();shown=products.filter(p=>[p.name,p.brand,p.category,p.description].join(" ").toLowerCase().includes(q));renderProducts();showPage("products")}
function filterByBrand(b){shown=products.filter(p=>p.brand===b);renderProducts();showPage("products")}
function filterByCategory(c){shown=products.filter(p=>p.category===c);renderProducts();showPage("products")}
function sortProducts(mode){shown.sort((a,b)=>mode==="low"?a.price-b.price:b.price-a.price);renderProducts()}
function renderBuilder(){const s=[products.find(p=>p.category==="Processor"),products.find(p=>p.category==="Graphics"),products.find(p=>p.category==="RAM"),products.find(p=>p.category==="Storage")].filter(Boolean);$("#builderGrid").innerHTML=s.map(p=>`<div class="builder-row"><div><b>${p.category}</b><br><span>${p.name}</span></div><b>${money(p.price)}</b></div>`).join("");$("#builderTotal").textContent=money(s.reduce((a,b)=>a+Number(b.price),0))}
function addBuild(){[products.find(p=>p.category==="Processor"),products.find(p=>p.category==="Graphics"),products.find(p=>p.category==="RAM"),products.find(p=>p.category==="Storage")].filter(Boolean).forEach(addToCart);showPage("cart")}
function addWishlist(){if(!currentProduct)return;const id=currentProduct.id||currentProduct.name;if(!wishlist.find(x=>x.id===id))wishlist.push({id,name:currentProduct.name,price:currentProduct.price});saveWishlist();toast("Added to wishlist")}
function renderWishlist(){if(!wishlist.length){$("#wishlistList").innerHTML="<h2>Your wishlist is empty</h2><p class='muted'>Add products from product detail page.</p>";return}$("#wishlistList").innerHTML=wishlist.map(w=>`<div class="list-row"><div><b>${w.name}</b><br><span>${money(w.price)}</span></div><button class="secondary" data-wish-remove="${w.id}">Remove</button></div>`).join("")}
function renderOrders(){if(!orders.length){$("#ordersList").innerHTML="<h2>No orders yet</h2><p class='muted'>When you submit checkout, orders will appear here.</p>";return}$("#ordersList").innerHTML=orders.map(o=>`<div class="list-row"><div><b>${o.name}</b><br><span>${o.phone} • ${o.address}</span><br><span>${o.items?.length||0} items</span></div><b>${money(o.total)}</b></div>`).join("")}
function renderAddresses(){if(!addresses.length){$("#addressesList").innerHTML="<p class='muted'>No saved address yet.</p>";return}$("#addressesList").innerHTML=addresses.map((a,i)=>`<div class="list-row"><div><b>${a.name}</b><br><span>${a.phone}</span><br><span>${a.address}</span></div><button class="secondary" data-address-remove="${i}">Remove</button></div>`).join("")}
async function submitOrder(){const name=$("#orderName").value.trim(),phone=$("#orderPhone").value.trim(),address=$("#orderAddress").value.trim(),notes=$("#orderNotes").value.trim();if(!name||!phone||!address)return msg("orderMsg","Please fill name, phone and address.","error");if(!cart.length)return msg("orderMsg","Cart is empty.","error");const total=cart.reduce((a,b)=>a+b.price*b.qty,0);const order={user_id:currentUser?.id||null,name,phone,address,notes,total,items:cart,status:"pending",created_at:new Date().toISOString()};let saved=false;if(dbReady){try{const {error}=await supabaseClient.from("orders").insert(order);if(error)throw error;saved=true}catch(e){console.warn(e)}}orders.unshift(order);saveOrders();cart=[];saveCart();renderCart();msg("orderMsg",saved?"Order saved to Supabase.":"Order saved locally. Database table not ready.","success")}
function saveAddress(){const a={name:$("#addressName").value.trim(),phone:$("#addressPhone").value.trim(),address:$("#addressText").value.trim()};if(!a.name||!a.phone||!a.address)return msg("addressMsg","Fill all address fields.","error");addresses.unshift(a);saveAddresses();renderAddresses();msg("addressMsg","Address saved.","success")}
function saveProfile(){localStorage.setItem("nova_profile",JSON.stringify({name:$("#profileName").value.trim(),phone:$("#profilePhone").value.trim()}));msg("profileMsg","Settings saved.","success")}
function msg(id,text,type="success"){const el=$("#"+id);if(!el)return;el.className="message "+type;el.textContent=text}
async function updateAuthUI(){const {data}=await supabaseClient.auth.getUser();currentUser=data.user;if(currentUser){$("#loggedOutBox").classList.add("hidden");$("#loggedInBox").classList.remove("hidden");$("#userEmail").textContent=currentUser.email;$$(".admin-only").forEach(x=>x.classList.toggle("hidden",currentUser.email!==cfg.admin))}else{$("#loggedOutBox").classList.remove("hidden");$("#loggedInBox").classList.add("hidden");$$(".admin-only").forEach(x=>x.classList.add("hidden"))}}
async function signUp(){const email=$("#signupEmail").value.trim(),password=$("#signupPassword").value,name=$("#signupName").value.trim(),phone=$("#signupPhone").value.trim();if(!email||!password)return msg("signupMsg","Enter email and password.","error");const {error}=await supabaseClient.auth.signUp({email,password,options:{data:{full_name:name,phone},emailRedirectTo:window.location.origin}});if(error)return msg("signupMsg",error.message,"error");msg("signupMsg","Account created. Check your email.","success")}
async function login(){const email=$("#loginEmail").value.trim(),password=$("#loginPassword").value;if(!email||!password)return msg("loginMsg","Enter email and password.","error");const {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)return msg("loginMsg",error.message,"error");await updateAuthUI();showPage("account")}
async function resetPassword(){const email=$("#loginEmail").value.trim();if(!email)return msg("loginMsg","Enter email first.","error");const {error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});if(error)return msg("loginMsg",error.message,"error");msg("loginMsg","Password reset email sent.","success")}
async function logout(){await supabaseClient.auth.signOut();await updateAuthUI();showPage("account")}
async function adminAddProduct(){if(!currentUser||currentUser.email!==cfg.admin)return msg("adminMsg","Admin only.","error");const p={name:$("#adminName").value.trim(),brand:$("#adminBrand").value.trim(),category:$("#adminCategory").value.trim(),price:Number($("#adminPrice").value),old_price:$("#adminOldPrice").value?Number($("#adminOldPrice").value):null,stock_qty:Number($("#adminStock").value||0),description:$("#adminDescription").value.trim(),discount:!!$("#adminOldPrice").value,type:"case"};if(!p.name||!p.brand||!p.category||!p.price)return msg("adminMsg","Fill required fields.","error");if(!dbReady)return msg("adminMsg","Run supabase-schema.sql first, then try again.","error");const {error}=await supabaseClient.from("products").insert(p);if(error)return msg("adminMsg",error.message,"error");msg("adminMsg","Product added.","success");loadProducts()}
function renderAdmin(){if($("#adminProductCount"))$("#adminProductCount").textContent=products.length;if($("#adminCartCount"))$("#adminCartCount").textContent=cart.reduce((a,b)=>a+b.qty,0)}
function toggleLang(){lang=lang==="en"?"ar":"en";document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.body.classList.toggle("rtl",lang==="ar");$("#langBtn").textContent=lang==="ar"?"English":"العربية";$$("[data-en]").forEach(el=>el.textContent=el.dataset[lang])}
document.addEventListener("click",e=>{const r=e.target.closest("[data-route]");if(r)showPage(r.dataset.route);const add=e.target.closest("[data-add]");if(add)addToCart(products[Number(add.dataset.add)]);const open=e.target.closest("[data-open]");if(open)openProduct(Number(open.dataset.open));const brand=e.target.closest("[data-brand]");if(brand)filterByBrand(brand.dataset.brand);const cat=e.target.closest("[data-category]");if(cat)filterByCategory(cat.dataset.category);const inc=e.target.closest("[data-inc]");if(inc){cart[inc.dataset.inc].qty++;saveCart();renderCart()}const dec=e.target.closest("[data-dec]");if(dec){let i=dec.dataset.dec;cart[i].qty=Math.max(1,cart[i].qty-1);saveCart();renderCart()}const rem=e.target.closest("[data-remove]");if(rem){cart.splice(rem.dataset.remove,1);saveCart();renderCart()}const wr=e.target.closest("[data-wish-remove]");if(wr){wishlist=wishlist.filter(x=>String(x.id)!==String(wr.dataset.wishRemove));saveWishlist();renderWishlist()}const ar=e.target.closest("[data-address-remove]");if(ar){addresses.splice(ar.dataset.addressRemove,1);saveAddresses();renderAddresses()}})
$("#menuBtn").addEventListener("click",openDrawer);$("#closeMenu").addEventListener("click",closeDrawer);$("#overlay").addEventListener("click",closeDrawer);$("#langBtn").addEventListener("click",toggleLang);$("#searchBtn").addEventListener("click",filterSearch);$("#globalSearchBtn").addEventListener("click",()=>{$("#searchInput").value=$("#globalSearch").value;filterSearch()});$("#showAll").addEventListener("click",()=>{shown=[...products];renderProducts()});$("#showDiscount").addEventListener("click",()=>{shown=products.filter(p=>p.discount);renderProducts()});$("#showStock").addEventListener("click",()=>{shown=products.filter(p=>p.stock_qty>0);renderProducts()});$("#showLowStock").addEventListener("click",()=>{shown=products.filter(p=>Number(p.stock_qty)===3);renderProducts()});$("#sortLow").addEventListener("click",()=>sortProducts("low"));$("#sortHigh").addEventListener("click",()=>sortProducts("high"));$("#detailAdd").addEventListener("click",()=>addToCart(currentProduct));$("#detailWishlist").addEventListener("click",addWishlist);$("#addBuildBtn").addEventListener("click",addBuild);$("#signupBtn").addEventListener("click",signUp);$("#loginBtn").addEventListener("click",login);$("#resetBtn").addEventListener("click",resetPassword);$("#accountLogoutBtn").addEventListener("click",logout);$("#accountLogoutSide").addEventListener("click",logout);$("#submitOrderBtn").addEventListener("click",submitOrder);$("#saveAddressBtn").addEventListener("click",saveAddress);$("#saveProfileBtn").addEventListener("click",saveProfile);$("#adminAddProduct").addEventListener("click",adminAddProduct);$("#reloadProducts").addEventListener("click",loadProducts);
supabaseClient.auth.onAuthStateChange(updateAuthUI);loadProducts();renderCart();renderOrders();renderWishlist();renderAddresses();updateAuthUI();
